export enum FormName {
  REGISTER_ACCOUNT = 'REGISTER_ACCOUNT',
  LOG_IN = 'LOG_IN',
  CHANGE_NAME = 'CHANGE_NAME',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  VERIFY_CHARACTER = 'VERIFY_CHARACTER',
  VENUE_LIST = 'VENUE_LIST',
  DELETE_VENUE = 'DELETE_VENUE',
  UPSERT_VENUE = 'UPSERT_VENUE'
}
